DROP TABLE IF EXISTS spotify_long_tracks;

CREATE TABLE spotify_long_tracks (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    artists TEXT NOT NULL
);

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('026O2YP2wRl9h3Ht9ClZST','Steady Rain in a Forest with Light Background Bird Chirping (Storm Ambience Sound Effects)',100,'Nature Sounds'),
('0DXnjJxJBvgMvBjG6Jug7I','Soundarya Lahari',66,'Mambalam Sisters'),
('6BFn78qFy9bRqKHTMfhnNv','Waves of Abundance & Fullfillment',60,'Zen Life Relax'),
('1dNwMOMtq3yflXibbqgLku','Mosquito Solution Anti Teen Street Party or Teenagers Loitering',45,'Device Sound Effect'),
('290gfei8moWWSh8qTVkTT3','Ibiza Sunset Tibetan Singing Bowl Sessions 7 (Wipe out All Negativity Inside You)',44,'Tibetan Singing Bowls'),
('23ordmf2KkRfHh9zE9RVyq','ä½ƒç¥­',35,'Gontaro Yanagiya'),
('47iSvlaCBugj3HrGZDZYcO','TÄ lÄ  Gaisma (Distant Light)',33,'PÄ“teris Vasks, O/Modernt Chamber Orchestra, Hugo Ticciati'),
('6fKZZf5Mws3hr31ZAvCOcs','Asmr Tea Massage Roleplay',32,'Jessica Cross'),
('4J08TVw9zNYeBUtSDIkLP6','Snuggling Up',31,'Relaxmydog'),
('1IPbXZ2OblHvSUY3Mj58iv','Keep Driving, Iâ€™m Dreaming',30,'Nicole LizÃ©e, Canada''s National Arts Centre Orchestra, Alexander Shelley'),
('0PHROMTH9aS7EP55Zqp5rU','DMT OBE Out of Body Experience Activation Frequency Spiritual Psychedelic Trip Sleep Meditation Music',30,'LOKOS TV Now Meditation Music'),
('4iipnIv7pu7ZJGnero0NRu','Music for Forests',29,'Len Leise'),
('3eSdS8uOOWA4WxpoY1iIWu','Uplift Yourself',29,'Sapien Medicine'),
('5JCaWBCMRZS8bjD9jTJas0','Ankh Uthi Mohabat Ne',28,'Nusrat Fateh Ali Khan'),
('27irP8iu2u5ppj1v8uhogx','Sourat An Naml',28,'Al Sheikh Ahmad Alnufais'),
('5vykLdfQeSwalNo8yuzdFW','å¡©åŽŸå¤šåŠ©ä¸€ä»£è¨˜-ã ‚ã Š(é ’é¦¬)ã ®åˆ¥ã‚Œ-2/2',27,'Utamaru Katsura'),
('41HGS4mcFudFQUCMrO7WPo','Livemiles II - Live in Berlin, Germany, 1987',27,'Tangerine Dream'),
('56xj0CztQ1OCzvUamYBoHz','Other Planes of There',22,'Sun Ra'),
('4l2wxY7OovHcSBjSiUGfxj','Videla (Parte 1)',21,'Felipe Pigna, Roberto MartÃ­nez'),
('1QV0W3OA8McFoE0NQL8MyX','Ar-Rum',20,'Edres Abkar'),
('6pzK39KuFvRt6F7Z7m279Q','Nirvana',20,'Satorio'),
('7yKuGwczYDibU86nvluyEm','Mental and Physical Relaxation - Remastered',20,'Emmett Miller, Steven Halpern'),
('5MHQpgP8IhG6nboW7mblVR','Senior 20 Minute Cardio Workout Mix (100 Bpm)',20,'Blue Claw Fitness'),
('5JIlNKHZZmIawokNxBVomi','Tite Karili',18,'Tha Lero'),
('5R5WKxp06Od9s05oUxSAsr','Symphony No. 7 in E Major, WAB 107 (Modified 1885 Version, Ed. A. Gutmann): I. Allegro moderato [Live]',18,'Anton Bruckner, Bavarian Radio Symphony Orchestra, Otto Klemperer');

-- CONTINUA...

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('56xpJB8aK1SXa5ACjAftGr','Manifestation Guided Shamanic Journey (With Drumming)',15,'Katie Weatherup'),
('70Mjj8raOAqYMlBK2hIv8C','Symphony No. 4 In C Major: I. Allegro molto moderato',15,'Franz Schmidt, Wiener Philharmoniker, Zubin Mehta'),
('7mIFUdhjiqzE9SFzFHkx2e','The Disanto Waystation',15,'S.E.T.I.'),
('7IkYKEH1aOrfA5YyN3MDlw','DiffÃ©rences (1959) - Remastered',15,'Luciano Berio, Institute for Computer Music and Sound Technology, Georg Kohler'),
('1BvPMdT9m0vCtFuPKAOo8d','Kumikyoku "Lucky Star Doga"',15,'Lucky Star no Minna'),
('6PuqdfSvPfEY4CwdBRvGC1','Cand S-Aduna Fratii Laolalta',15,'Ionela Pascu'),
('61rTznv1hAj5xgnAPxTeZ3','Uyumayan Ã‡ocuklara Ninniler',14,'KÃ¼Ã§Ã¼k Murat'),
('3tEnHrxfFbUzPEw1Q4xx8U','Septet No. 1 in D Minor, Op. 74: I. Allegro con spirito',14,'Johann Nepomuk Hummel, Dieter KlÃ¶cker, Florian Uhlig, Consortium Classicum'),
('06SRK5lDgngG0cNVYCQOo6','Overture "Leonore No. 3", Op. 72b',13,'Ludwig van Beethoven, Berliner Philharmoniker, Herbert von Karajan'),
('0stLtEEUQlwwSr8PKnmqMj','Ø³Ø§Ø¹Ù‡ ÙˆØªØºÙŠØ¨ Ø§Ù„Ø´Ù…Ø³',13,'Hatem Al Iraqi'),
('5i4RxlZwqYCGufcaOZJ5Uu','The Rabbit',13,'Lucas King'),
('54K3QQLtubkMsNBEGFtc90','TannhÃ¤user, WWV 70: Overture',13,'Richard Wagner, Stuttgart Radio Symphony Orchestra, Hans MÃ¼ller-Kray'),
('3DPIlF35nVa6Xvgn6LCajU','Abankusele',13,'Herman Basudde'),
('5kD2vf3VXg0lxa3hdBUaHq','Symphony No. 7 in E Major, WAB 107 (Ed. Haas): IV. Finale. Bewegt, doch nicht schnell',13,'Anton Bruckner, Wiener Philharmoniker, Herbert von Karajan'),
('7x7l3MioySWBqjpXbCOvbD','Cello Concerto in A Minor, Op. posth.: II. Adagio molto tranquillo',12,'Hans Pfitzner, Rundfunk-Sinfonieorchester Berlin, Alban Gerhardt, Sebastian Weigle'),
('5bz2zkO6hVnP6c7iSpSgRF','Genocide for Praise - Vals for the Vitruvian Man',12,'Allegaeon'),
('2ZeSzc0OGcTmPFn4fSisWj','Cello Concerto In B Minor, Op. 104, B.191: 3. Finale (Allegro moderato)',12,'AntonÃ­n DvoÅ™Ã¡k, Alisa Weilerstein, Czech Philharmonic, JiÅ™Ã­ BÄ›lohlÃ¡vek'),
('1tqbZQHyXAruQp6Dkupa6L','Sonata for Viola and Piano, Op. 36: I. Maestoso allegro',12,'Dimitri Murrath, Vincent PlanÃ¨s'),
('4nlyt76hbZdzX6Zcs3ZPLS','Chit Tha Mya Ko',12,'Win Oo'),
('1MwpNTd8dc2qfvmhLnMxaN','Cello Concerto No. 2 in C Minor, Op. 77: I. Molto sostenuto - Allegro molto e energico - Tempo I -',12,'Dmitry Kabalevsky, Torleif ThedÃ©en, Hannover Radio Philharmonic Orchestra, Eiji Oue'),
('5yFoKbVuVoA19NjP1j7qBu','String Quartet No. 12, Op. 127: II. Adagio, ma non troppo e molto cantabile',11,'Ludwig van Beethoven, The Beethoven Quartet'),
('2AgriLe23vg8NV40qLKDif','Ù…ÙˆØ§Ù„ Ù†Ø§Ø³ ØªØ¬Ø±Ù‰ ÙˆØ±Ø§ Ø§Ù„Ù…Ø§Ù„',11,'Ù…ÙƒØ±Ù… Ø§Ù„Ù…Ù†ÙŠØ§ÙˆÙŠ'),
('6doPx9QArdfAZj92U48nAe','Alone Again',11,'Bvdub'),
('0UtwGOSlMenvrKD3zrfstB','é ˆå±±æ¸…å¢ƒåƒ§',11,'å¦™è“®è ¯'),
('1WQ2cb21bem9zYChpaesBM','Children of the Sounds',11,'Kaipa'),
('65MDXHYuMqboPfcoxgDz3m','Living on the Ceiling - Tuesday Morning Door Policy Version',11,'Skinnerbox'),
('71eTQdcUvHiAReUQ6Rsl3M','Cosmic Sensations',11,'Sweet Carol'),
('3mnMDiz81wtKoFbPisgmca','Mokili e change - Live',11,'ZaÃ¯ko Langa Langa, Nkolo Mboka'),
('7lI7BksTQwiLX7y9Y94DaT','Can''t Go Home - Live at Paradiso',10,'King of the World'),
('3qF9WiYP6EyHbWoAmoKpQS','Polonaise in F-Sharp Minor, Op. 44',10,'FrÃ©dÃ©ric Chopin, Folke Nauta'),
('1ddJ3rTJquZSkrQyAUQNik','Hia li gabratni - Live',10,'Cheb Hichem'),
('0pPN0Lx1hKBAULV84OnhB1','Third Eye',10,'Macroform'),
('2UVZtm5kUGxK5bJaxd7fpX','Shavasana',10,'Howard Givens, Craig Padilla'),
('2ojN2LMlmaYjouKXmWT3zE','In This Moment',10,'Dayspring Worship, Joel Wiseman'),
('2UVpWB2qeYKfHkCA9VhdOL','Mozart: Quintet for Piano and Winds in E-Flat Major, K. 452: I. Largo - Allegro moderato',10,'Wolfgang Amadeus Mozart, Les Vents FranÃ§ais'),
('4KJu1hYFLyxzbYm1vwqF6G','Tiamat',10,'Musarra'),
('4aOpBWbs3XUMuWgMbsM31d','Sich rundherum wohlfÃ¼hlen',9,'Nora del Mar'),
('5SQYozFvOZsmcLFG7MS9Il','ã€œå¼•ã  å¯„ã ›ã ®éŸ³æ¥½ã€œ æ³¢å‹•ã‚’ä¸Šã ’å…¨ã ¦ã ®â€œè‰¯ã  ã‚‚ã ®â€ ã‚’å¼•ã  å¯„ã ›ã‚‹éŸ³æ¥½ / Î±æ³¢ / ãƒ¨ã‚¬ / çž‘æƒ³ / é›†ä¸­åŠ›',9,'Relaxing888'),
('0UxlQIoG9CJRXlJkUeKydH','MnWa3at 11',9,'Arabic Djs, Arabic DJ'),
('0ZCVUCrng6jswYGY9smSlr','Sonata for Violin and Piano No. 5 in F, Op. 24 - "Spring": 1. Allegro',9,'Ludwig van Beethoven, Ji Hae Park, Simon Lepper'),
('0wn8T4fxqEPwZDbxQI67v2','Stars',9,'Barry Jamieson'),
('4aoVGSTaXC70ld38dEJ1L4','Timeless - Orchestral Trance Intro Mix',9,'Kelly Andrew'),
('6y3wS0FvyBI0kL3MTT4sJT','Violin Concerto No. 3 in G Major, K. 216: I. Allegro',9,'Wolfgang Amadeus Mozart, Eduardo Marturet, Emmy Verhey, Royal Concertgebouw Orchestra'),
('4IFpA7qxzZlASw2RDgWpX8','Hispania - Spanish Fantasy for Symphony Orchestra [Live]',9,'Oscar Navarro Gonzalez, Oscar Navarro, Oscar Navarro Symphony Orchestra'),
('4WVwrKyzCL5AjBtpKAZEOZ','Limbs',9,'Endless Ocean'),
('27oWBjpSdNlvL9T44EtE50','Deep In The Night',9,'New Members'),
('5DlU9BjHN5xWHUEEzvO1dW','Shirt of Noise',9,'Lee Weisert, Clara Yang, Juan Alamo'),
('731OdH0hiFrSx5DJBVRaFS','Pampeana No. 1, Op. 16',9,'Alberto Ginastera, Donald Sulzen, Henry Raudales');

--CONTINUA--

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('2UNzMQV3pnFHOBIkLy3Lck','Anamnisi - Hot TuneiK Remix',9,'Jorgio Kioris, Simos Tagias, Hot Tuneik'),
('0ZNz2b9tcLIqAp4U8luv6Y','Broken Corners',9,'1 Mile North'),
('6GJBiVE29cVKnYIO1xFZzC','The Diving Bell',9,'Black Foxxes'),
('5mhT9FupmaYktfc70v2rl7','Feet First',9,'Z-Arc'),
('3Pz4sWKMmNEfIGbkCdbaeO','Pesther Kinder - Walzer, Op.42',9,'Carl Michael Ziehrer, Original C.M.Ziehrer Orchester, Hans Schadenbauer'),
('25jQFzEpFaOxzQPqEBlB30','The Water Is Troubled - Medley',9,'George Banton'),
('4VkQ3tr2sCBkaIIkT2DOXT','Suffocating Hopes',9,'Mourners Lament'),
('4fW7lh5F5jJsiQ1bShWrzi','Space and Silence',9,'Loom, Dopadocks'),
('5okhIOGE78yApy9u5xHY6k','Fortunated - Original Mix',8,'Invisible Reality, Klopfgeister'),
('3YBbkEIF6Asp6enBInOEPv','Istanbul',8,'Derya TÃ¼rkan, Sokratis Sinopoulos'),
('5zs55cpupKKCqf80kOPPfp','Actuate',8,'Bongo & Pusk'),
('62oCcVXa7MMLriwisllCK2','Flight',8,'Dren McDonald'),
('5PSl4song5Iunx0NdOqYzZ','The Holy Name',8,'Cornershop'),
('6mH2Q6zvqxQc6gR96NKrl5','Way Maker - Live',8,'Glaubenszentrum Live, Markus Muntean'),
('3Lf4SCSNXHs021y3zw5di2','Images for Orchestra, CD 118: II. IbÃ©ria: b. Les parfums de la nuit - Live',8,'Claude Debussy, Orchestra dell''Accademia Nazionale di Santa Cecilia, Leonard Bernstein'),
('2M5QLUDgc2EKOHMSYUdoNs','Voryva',8,'Dzivia'),
('3Ekq3wshgiNiAHH88KZxLE','Sans Lendemain',8,'Vous Autres'),
('4L7qr0rd7px1ajgRN7tZOt','Another Trip - Sidhartha Remix',8,'Alienn'),
('0dnrweX1MbuZD50M2b8Fw7','Alive Again - Live',8,'Trey Anastasio'),
('4dkO8R3zCC1SCNuhzcPHbz','Das Flores Das Ã guas (feat. Shimshai)',8,'Alexa Sunshine Rose, Shimshai'),
('6YNyXhUBsj5f1w06r4m2bw','Get Up High',8,'Cyril'),
('1fglXTyRSChB72Mq5TK4Ne','The Great Pyramid of Cheops',8,'Andawan'),
('4b6WJ41qKWGUMZB7cHTF0d','Lal Meri Patt - Live',8,'Sanam Marvi'),
('4xg6i3qL3TPsYm9qU5A7kr','Awaiting Resurrection',8,'Drive-By Truckers'),
('6QCJkly15KWNRy7QrYzjrE','Tony Touch Power Cypha 2 Freestyle ''97',8,'O.C., Fat Joe, Lord Finesse, Big L, A.G., Diamond D'),
('1aL9QCWR1ZxZpuY2q37PIk','Contact',8,'Mindwave'),
('4tmoVFcX4e0z1DfYUhfjpK','La Gozadera 7: LÃ¡grimas de Cristal / Una LÃ¡grima / AdiÃ³s Amor AdiiÃ³s Mi Amor Te Vas / Te Quiero para MÃ­ - En Vivo',8,'Marimba Orquesta La Gran Manzana'),
('3pXIEp6hW1BSNYW6KvPtlN','ã ‹ã ‘ã ¦ è§£ã   ã  ã ®å¿ƒã ¯',8,'yeahyoutoo'),
('2Qi4vMeWu6LBSaZbASdau3','Neverland',8,'Dyce'),
('4KqRCPvv446WhB6FcJOMfP','Spem in Alium and Her Unable',8,'Kyle Bobby Dunn'),
('4mxtrjWiflBH2izYC6rYvt','Mondo Buzzo',8,'Causa Sui'),
('7ovSaBFemf4lmZDpPeVBn4','Cka po m''rrin karshi karshi',8,'Ali Krasniqi, Halil Bytyqi'),
('7kn82QLjGE0dIRRX67klbG','King Christian II, Op. 27: V. Nocturne',8,'Jean Sibelius, Turku Philharmonic Orchestra, Leif Segerstam'),
('2YiHJSN7sNQExtdeZnL8MN','Oceans',8,'Alpha Gravity'),
('2nU3IMWjgkxvtQeaMlyc9f','Breakmay',8,'Osvit'),
('52N53mNNunNUQFWmtGqFG7','Loup the Loup - Live',8,'Matthew Fries, Phil Palombi'),
('0vXKORBq2RHPYGAeNBkBzd','Recuerdos de Amor: Lo Que No Fue No SerÃ¡ / Amar y Querer / O TÃº o Yo / El Triste / VolcÃ¡n / GavilÃ¡n o Paloma - Instrumental',8,'Orquesta Amor Latino'),
('2Jgq6HT6VGHq5fHUan0Bzb','Smyrna',8,'KHAIKHAN, Dest'),
('1LvNuDHeQ0ibGiEzwRdq1L','Unique',8,'Simon Le Grec'),
('1AhSl55K5EQbTbFXr35gQZ','Igraj Mare PraÅ¡ina Se DiÅ¾e / Trusa',8,'Mate Bulic'),
('5RjbOEO1W9FymAzvB9G9vg','These Ties Are Binding - Original Mix',8,'Andres Sanchez, Katherine Amy'),
('4ZILOfRVBFNMcRxXqPNS1t','Il chitarrista',8,'Ivan Graziani'),
('6CRRlM7Phug9Gj3S4Rk8Xr','To the Throats',8,'Antlers'),
('0hCVS9jZrgEXdAt47EQDqa','Tu Agar Benaqab Ho Jaye',8,'Nusrat Fateh Ali Khan'),
('33K1hgLpTBAN0OdcwwVIjG','Wabi Sabi',8,'Pspiralife'),
('1SABG47KTubx9SahfMrZRA','Halo On Fire',8,'Metallica'),
('1COyK5IMdf2fdy7HCsc5a1','Faddah',8,'Hossam Ramzy'),
('6kKrTjTIuBuzlI0jXg7bY1','Meditation Â»Zeichen eines VerstorbenenÂ«',8,'Pascal Voggenhuber'),
('2SyfyabWQz7arAiHoJSZYU','Noche',8,'Jacky Mingo, Kapote'),
('6wrGrOBWeiPxPhkJoBV95v','Symphony No. 9 in E Minor, Op. 95, B. 178, "From the New World": II. Largo',8,'AntonÃ­n DvoÅ™Ã¡k, Northern String Quartet'),
('2MpXY4OOal7LnKkI9mfpof','Last Knockers - Original Mix',8,'Crazy P'),
('3DTqJhZgZxhzVF4SLvdwPB','Srila Prabhupada Pranati and Maha Mantra (Live)',8,'Harinama Ruci'),
('17cChhy58DYKXd6WbNk7xb','Sajana - Beloved',8,'Susheela Raman'),
('1CiJ8vEnuoKDxNvvaCGJiN','ØµØ¯Ø§Ù…ÙŠØ© Ù„Ù„Ù…ÙˆØª',8,'Gazal Alabedallah'),
('7oQAi0ZX649fLxSpvSSyYO','Amigo',8,'The Mansisters'),
('4r6R29US2FnvbQzeAdX52U','Baion - Original Club Mix',8,'Federico Scavo');

--CNTIJNUA--

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('422fCC4DLocxxv3XInJx1z','Neukliana - Kay-D Remix',8,'Ricardo Piedra, Kay-D'),
('3vYKjyy15FutB3FggySyK3','It Turns For You - The Noble Six Remix',8,'Neptune Project, Polly Strange, The Noble Six'),
('6FOhLZtbYhbaHeL6oM8CEi','Symphony No. 9 in E Minor, Op. 95, B. 178 "From the New World": III. Scherzo. Molto vivace',8,'AntonÃ­n DvoÅ™Ã¡k, Budapest Philharmonic Orchestra, Stephen Pomerantz'),
('3b2aul5zbmRoaT3GaN4VN0','Symphony No. 6 in B Minor, Op. 74, TH 30 "PathÃ©tique": II. Allegro con grazia',8,'Pyotr Ilyich Tchaikovsky, Philharmonia Orchestra, Sir Charles Mackerras'),
('6Fl6S9ygFos67pEr5FpC4x','Angels',8,'John Tavener, Andrew Lumsden, Winchester Cathedral Choir, George Castle'),
('1VLnC046WJSTGiikbuUcIR','El Nazareno',8,'Miguel ZenÃ³n'),
('6MQOHKsRkWgGElHJDBN0Xs','Have a Little Mercy',8,'Jimmy Dawkins'),
('7cMOQlwKhsuNGXRziRYYPz','Them Changes',7,'Tommy Castro'),
('75IBM2boZhRhxhGP87CmOm','Cold Blooded Blues - Live',7,'Mike Casey'),
('4ewEBSsKwC0VlPihqVOIQr','Michigan - Original Mix',7,'Ralph Myerz, R.E.C., Ryan James, SUPER SPACE PROJECT'),
('4kD6VrXFdzcGwWKk9hyRxv','Something More (Dirty)',7,'RÃ³isÃ­n Murphy, Crooked Man'),
('1gMx1IbvsNXkpijQz1eMcy','Sage Bhai KO Zahar Hash Ke Pila Dete Hai Log',7,'CHANDAN SHARMA HATHRASI'),
('1WHp6DRSAf5bnc64PVmjwj','S''il te plaÃ®t',7,'HÃ©ritier Wata'),
('3xiLl8VQERFlPbQ0xogLSu','Youreoneofakind',7,'Spencer Parker'),
('5XDbAqepMVv4fRfZeeK6x7','Going Down - Woo2tech Remix',7,'Andruss'),
('7nIIaSnAqhgW7uvRF8t8Qf','Vicia Faba',7,'FELIZ'),
('0GNV9yC7KnYsxFItDMarXb','Wicked Game - Criss Source Remix',7,'Solarc, Criss Source'),
('7bEyYaCovAMVSEsF5iUS9x','Hold Me Down',7,'Funk You'),
('4Dx0Uga2EfspDoPMRu62wH','Passenger',7,'Kamilo Sanclemente'),
('1KrpWHU4t2W5ButVUX4wOb','Keep Rockin'' (Thumping House Mix)',7,'Love From San Francisco'),
('3ryYkBhszo4ioSxfshM3F6','Brooklyn - Original Mix',7,'Traumton'),
('3PJwafHSStf0QiDQ17XzC9','Walking Individuum',7,'Casimir Von Oettingen'),
('7lHq5EAEJl2uTo5smYihds','Theory of Happiness',7,'ãƒ’ãƒ¼ãƒªãƒ³ã‚°ãƒ»ãƒ©ã‚¤ãƒ•'),
('5DTkIoX7EzgoYElepGBeQb','A7 - Original Mix',7,'Shai T'),
('6Zdu2JM44pVKvia0Kpxk9n','Topkapi',7,'Rhyton'),
('78SXI6mx1LIavJMIZy6yMF','Ei Horinaam Ei Mohanaam',7,'Uttam Kumar Mondal'),
('7yPyQdA0bwEFrDKi0wr6mQ','Ouija',7,'Perception'),
('6FSC5JYPEibYenoQCcOxZ8','Come Alive (feat. Toro y Moi) - Grum Remix',7,'Chromeo, Toro y Moi'),
('4YzkH5cj9HQpTd59yjKmZy','Kronos',7,'Boy Next Door'),
('3vzbsbfBNzOfiSZpTquvo9','Thank You Lord - Victor Simonelli Gospel Club Mix',7,'Connie Harvey');

--CONTINUA--

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('4U0B7HH1PNt6DZy6hzcCA6','Oxygen - Wayne Madiedo Remix',7,'Andres Blows'),
('6ydRp3pmWeFAAZPiqkcUvw','Gharawa Aawa Ae Sajanawa',7,'Sonu Sargam Yadav'),
('2ocstW4LaFRioaXbzm626L','Betrayed Mayan Blood',7,'Seol'),
('2Q56v0AU3bCO9OOYeDXzLF','Neobzriem Sa SpÃ¤Å¥',7,'Dominika GurbaÄ¾ovÃ¡'),
('0Gbahme97ZYgeltOD6JOIZ','Mathematics',7,'North Coast Vibes, Rob G'),
('0HoQRjNKQGbeAUTurm459I','Teapot - Original Mix',7,'Cristoph'),
('7nQ6uJYXYxlEpX4YQ7CCzh','String Quintet No. 4 in G Minor, K. 516: III. Adagio ma non troppo',7,'Wolfgang Amadeus Mozart, Anna Maunther, Tatrai Quartet'),
('1LyMYb6U18K1f0aHoSbdHB','Spuren',7,'Pablo Held Trio, Pablo Held, Robert Landfermann, Jonas Burgwinkel'),
('4RoiAgoRJpomN0CJsuBbs3','Extra Vehicular Activity',7,'Alessandro Penna'),
('24hSXqLEK1BlycJeYiy4f3','2016 Golden Era Cypher (feat. Hilltop Hoods, the Funkoars, a.B. Original, Briggs, Vents, K21 & Purpose)',7,'Golden Era Records, Hilltop Hoods, Funkoars, A.B. Original, Briggs, Vents, K21, Purpose'),
('6QGuVRLWa5c2q9FlS2aI74','Vanished Days, Op.57, No.1',7,'Edvard Grieg, Mikhail Pletnev'),
('4TIZlTcIyOlxcNEeT4N0PO','Borje Aaj',7,'Shahrokh'),
('2na0H7wMDXpocnjCd2cbnI','Perspective',7,'Pragmatix'),
('5obsAfjix98sySbWohthlw','L''amour Toujours',7,'Antonio Venuti & Mr Goaty'),
('2zT1Vr67S4Pjlg8w6x5Oca','Cookies N`Cream',7,'Kayros, JoÃ£o Oliveira'),
('7w1IDcPTeNdG7x1kOahFqM','Pushin'' On - Original Mix',7,'Phase 2'),
('2C4h5x1lwt6AJ0F8VM5UGi','Ship of Fools - Live at Red Rocks Amphitheatre, Morrison, CO 7/8/78',7,'Grateful Dead'),
('4mH0PDh94bo0OT6PYTpm0V','Violins',7,'DJ Tarkan'),
('1QB5P585UMxd7ECzsIep8h','Immortal - Original Mix',7,'Alfoa'),
('4tKwGgmGoZt9vPhZb1Z5yx','Little Helper 336-2',7,'Stefano Noferini, Looad'),
('28PmfUGQO1CK6KXKZWUwcW','Ghetto Break',7,'Jason Bye'),
('5t0KoOCCj8IDCZc9lNXnCr','7 Seconds',7,'Ben DJ'),
('5tDbYmuxnQlh0Xxra1SMWt','Particles',7,'Tony Anderson'),
('36JYPF6D9DmCZRSgsDYVAX','Moon Cat - Dj San Remix',7,'Max Freegrant, Max Meyer, DJ San'),
('1CseRS3c1cQSvYyHSPhnNz','Sweet - George Morel Remix',7,'Frank Donner, George Morel, Stefan Mint'),
('2wxehv10ykM4c64Jsi7CRz','Atma - Avus Remix',7,'Birdcage, Avus'),
('0ULvYLGWZw3VWEsqJ6pDzm','Salajka',7,'Lag'),
('5IJvj7XTw3kUTbWgTv0VAq','Makibishi',7,'Simina Grigoriu'),
('73yp98F2ESKnHLT4lgqr5Z','Mori Gagar Na (Teental)',7,'Traditional, Gulshan Tandon'),
('6MEmZsicSod5jLvdwaMvXY','Please Have Mercy On Me - Dj Umbi Deep Remix',7,'Big Mojo');

--CONTINUA--

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('0soVbyUAgY8tgzdiRog7xU','First Loved Me - High Key Without Background Vocals',7,'Covenant Worship'),
('7i0El4yOp6embW4ZKYpYGO','Minor - Original Mix',7,'Dirty Culture, Nusha'),
('6AqPwpSugDmDIF3QAWHyBj','Piaaaaach!!',7,'Dj Marta, Tim Wokan'),
('7BXOLFVdf4SNkI8kGvbrbF','Sahar',7,'Jose Solano, Cafe De Anatolia'),
('5QDr9jdPLphwabjLBmzdsU','On the Edge of Existence',7,'Bernd Kistenmacher'),
('7qI17QKuUacxqXD3xoO8FB','Money',7,'Gov''t Mule'),
('17u3p1rzVRfbmWETYO1WPd','Gives Me Statisfaction (128 Bpm - Seat Climbing / 70-75 Hf Intensity)',7,'SKYGO'),
('36v1Mc96ANEFSePURfAUll','From Disco to the Underground - James Rod Remix',7,'Limpodisco, James Rod'),
('4sueXHAbsmaoUjmZqUA3gN','Caminante',7,'Bender, Nina'),
('1b40rkIU0jsz5TdEFKKxql','Desert Dreams - Original Mix',7,'Valeron, 7even (GR)'),
('2hzBwTPpPndXh9bOFrqdUq','Red Eyed Viper - Original Mix',7,'Elek3ctii'),
('5act0f9sWFwQ8cswUDwOXj','Cherie Nobato',7,'Wuta Mayi'),
('0wtOJWgGXIHlOAfiOJXRW4','Shining',7,'Cosmic Replicant'),
('5IRP2EyJ3BjmEPd2lYJk18','Invasion',7,'Anna Lee'),
('6RrzrhPCm0tAtDUzqzURc9','Skullgroove',7,'Mijo'),
('5UbrywfBOKQwMeUZiSAUtH','Tonight You Sleep In Hell',7,'Boris S.'),
('7LNj462j5jchQjtXJApa2o','Interference',7,'Massa (7)'),
('5XUj5BiQdpzDRiHNYE3V47','60c - Original Mix',7,'Noneoftheabove'),
('0W6EGWsAFml7FWIweiOx4E','Baghia Tatezaoudji Ou Tkhalini',7,'Cheb Houssem'),
('4jIM9xhhJrqekOItxi8702','Camden Square',7,'Butcher Brown'),
('6AipXB8ttXKoE8y91rYwER','Golden Glow',7,'Prince Rama'),
('3IEVly6NxeK07CWoDAapZm','Free Man',7,'Dj Fudalwokit'),
('3LcZPbJgzbI2DCv5D5XDIB','It''s All About Me - Original Mix',7,'Green Velvet, Jay Lumen'),
('4w8Ypike64pHZ6KFmk1VPj','Looking Beyond',7,'Roger Spees'),
('7CBj8rqMRX5wGTxJNGLWIk','Opening Ceremony',7,'Ã“perentzia'),
('4YTphPjdWVfNJe1OkY1maV','Saha',7,'Stereo Express'),
('1LIy2e7ODs7J8GdQoAkR2v','Won''t Say It - Henry Saiz Remix',7,'bRUNA, Henry Saiz'),
('1saIZVjM5EI6fhK2eT8u5W','To the Right the Enemy, To the Left the Sea',7,'Simon Rackham'),
('0OYKGPqjJjKiFJvv0ncSvr','Los Versos Se Me Van',7,'Sincroniza2'),
('5xMuFJgdjOUgfdnG6yxptP','Kapitel 1 & Kapitel 2.1 - Die PrÃ¼fung',7,'Kim Jens Witzenleiter, Wolfy-Office');

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('7xQ2mVnP5kL8dT1rF4cWsY','Fractal Universe',5,'Tripswitch'),
('5mV1xQnR4kL7dT2pF8cWsY','Solar Winds',5,'Solar Quest'),
('2nQ8xVmP1kL4dT7rF5cWsY','Nightfall Meditation',5,'Lama Gyurme'),
('9mV5xQnR2kL1dT4pF7cWsY','Mystic River',5,'Aeoliah'),
('3xQ1mVnP7kL4dT2rF8cWsY','Sacred Breath',5,'Steven Halpern'),
('1mV8xQnR5kL2dT1pF4cWsY','Floating Temple',5,'Banco de Gaia'),
('8xQ4mVnP1kL7dT2rF5cWsY','Deep Awakening',5,'Zen Baboon'),
('6mV2xQnR7kL5dT1pF8cWsY','Mystical Dreams',5,'Kamal'),
('4xQ1mVnP8kL2dT5rF7cWsY','Hidden Paradise',5,'Blue Planet Corporation'),
('7mV5xQnR1kL4dT2pF8cWsY','The Infinite Gate',5,'Nibana');

INSERT INTO spotify_long_tracks (id, name, duration_minutes, artists) VALUES
('1jD5r7xGQfM9Xkq9d0lV8A','Celestial Awakening',6,'Dreamstate Logic'),
('6K0s4Hqf0Yzj3bUtVn5zKQ','Echoes Through Eternity',6,'Solar Fields'),
('2xQw7MnaT5d3LxA1b0QmFp','Whispers of Tibet',6,'Sacred Earth'),
('4mD8xYwPq3nJ5sK0tR7uVc','Moonlit Reflections',6,'Liquid Mind'),
('7qN9cVxP2mL4dF8sK1aJHt','Into the Deep Void',6,'Carbon Based Lifeforms'),
('3tR5mKxQ8pV1dN6yH2wLsF','Forgotten Temples',6,'Mystic Crock'),
('0uV7kLqW5nX3mC8bJ9rFpD','Winds of the Sahara',6,'Desert Dwellers'),
('5nT2aXqR7mL8pK3dV0wFsJ','Infinite Horizons',6,'Bluetech'),
('2cY4pVnQ9mK6tL1xR8wFdS','Ancient Rituals',6,'Shulman'),
('8mF5xQvN2kL7dP1rT4wCsY','Oceanic Dreams',6,'Aes Dana'),
('4kP7xNwQ1mT8dL3vR5cFsJ','Temple of Light',6,'Entheogenic'),
('6wR2mVxQ9kL1pD4tF7cNsY','Shamanic Voyage',6,'Globular'),
('1nQ5vKxR8mT2dL7pF4wCsY','Beyond the Stars',6,'Asura'),
('9pL4xQvN7mK2dT1rF8wCsY','Mysteries of Avalon',6,'Cell'),
('7mX2qVnP5kL8dT1rF4wCsY','Dreamwalker',6,'Kick Bong'),
('3wQ7mVxN1kL4dT8pF2rCsY','Inner Peace Meditation',6,'Meditative Mind'),
('5xN2qVwP8mL1dT4rF7cKsY','Healing Frequencies',6,'432Hz Universe'),
('1rV7mQxN4kL2dT8pF5cWsY','Spirit of the Forest',6,'Llewellyn'),
('8kQ2mVxP5nL7dT1rF4cWsY','Floating Between Worlds',6,'Astropilot'),
('2mV5xQnR8kL1dT4pF7cWsY','Zen Garden',6,'Deuter'),
('6qN1xVwP4mL7dT2rF8cKsY','Cosmic Drift',6,'Suduaya'),
('4pX7mQvN1kL5dT8rF2cWsY','Awakening Consciousness',6,'Ajja'),
('7vQ2mXnP5kL8dT1rF4cWsY','Sacred Mountains',6,'Medwyn Goodall'),
('5mN8xQvR2kL1dT4pF7cWsY','Third Eye Activation',6,'Binaural Beats Therapy'),
('2xV5mQnP7kL4dT1rF8cWsY','Transcendence',6,'Koan'),
('9wQ1mVxN4kL7dT2pF5cRsY','Hidden Dimensions',6,'E-Mantra'),
('3mX8qVnP2kL5dT1rF4cWsY','Silence of the Ancients',6,'Alwoods'),
('1pQ4mVxR7kL2dT8nF5cWsY','Crystal Caverns',6,'Zero Cult'),
('8nV2xQmP5kL1dT4rF7cWsY','Timeless Journey',6,'Ishq'),
('6mQ7xVnR1kL4dT8pF2cWsY','Echoes of Atlantis',6,'Chronos'),
('4xN1mQvP7kL5dT2rF8cWsY','Astral Projection',6,'Mindwave'),
('7mV4xQnR2kL8dT1pF5cWsY','Meditation in Blue',6,'Anugama'),
('5qX1mVnP4kL7dT2rF8cWsY','Eternal Flow',6,'Govinda'),
('2mQ8xVnR5kL1dT4pF7cWsY','Sunrise Over Himalayas',6,'Karunesh'),
('9nV1xQmP7kL4dT2rF5cWsY','Deep Space Resonance',6,'AES DANA'),
('3mQ5xVnR8kL2dT1pF4cWsY','Silent Pathways',6,'Miten'),
('1xV7mQnP4kL8dT2rF5cWsY','Journey Beyond Time',6,'Tya'),
('8mQ2xVnR5kL1dT4pF7cWsY','Forest Spirits',6,'Dan Gibson'),
('6nV4xQmP1kL7dT2rF8cWsY','Mind Expansion',6,'Hinkstep'),
('4mQ1xVnR7kL5dT2pF8cWsY','The Last Horizon',6,'Connect.Ohm');

SELECT name, artists, duration_minutes FROM spotify_long_tracks WHERE duration_minutes >= 20 ORDER BY duration_minutes DESC;
SELECT * from spotify_long_tracks where duration_minutes >= 8 AND duration_minutes <= 15 AND name ILIKE '%Orchestra%' ORDER BY name ASC;
SELECT COUNT  (*) AS total_tracks, AVG(duration_minutes) AS avg_duration, MAX(duration_minutes) AS max_duration, MIN(duration_minutes) AS min_duration FROM spotify_long_tracks;
SELECT artists, COUNT(*) AS total_tracks, AVG(duration_minutes) AS avg_duration FROM spotify_long_tracks GROUP BY artists ORDER BY total_tracks DESC LIMIT 10;
SELECT name,artists,duration_minutes,duration_minutes - AVG(duration_minutes) OVER() AS difference_from_avg FROM spotify_long_tracks WHERE duration_minutes > (SELECT AVG(duration_minutes) FROM spotify_long_tracks) ORDER BY duration_minutes DESC;